window.werchterArtistImages = {
  "Triggerfinger": {
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Pinkpop%202018%20-%20Triggerfinger%203%20(cropped).jpg?width=520",
    "source": "https://www.wikidata.org/wiki/Q305326",
    "title": "Triggerfinger",
    "provider": "Wikidata/Wikimedia Commons"
  },
  "Yong Yello": {
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Yong%20Yello.jpg?width=520",
    "source": "https://www.wikidata.org/wiki/Q118194401",
    "title": "Yong Yello",
    "provider": "Wikidata/Wikimedia Commons"
  },
  "Zwangere Guy": {
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Zwangere%20Guy%20(2026).png?width=520",
    "source": "https://www.wikidata.org/wiki/Q30524684",
    "title": "Zwangere Guy",
    "provider": "Wikidata/Wikimedia Commons"
  }
};

window.werchterArtistImageMeta = {
  "source": "Rock Werchter official act images first; Wikipedia/Wikimedia/Wikidata where available",
  "generatedAt": "2026-07-01T21:57:56.068Z",
  "found": 3,
  "total": 144,
  "official": 0,
  "wikimedia": 3,
  "fallback": "Generated artist-name tile for acts without a reliable online image",
  "stillMissing": [
    "Kasabian",
    "The Lumineers",
    "The War on Drugs",
    "Mumford & Sons",
    "Balu Brigada",
    "All Them Witches",
    "The Vaccines",
    "Loyle Carner",
    "JADE",
    "The Prodigy",
    "Monza",
    "Bente",
    "Yard Act",
    "Dylan Gossett",
    "Tom Smith",
    "Blood Incantation",
    "Ben Ellis",
    "Basht.",
    "LA LOM",
    "Karen Dió",
    "PUP",
    "Midnight Generation",
    "Lovelee Days",
    "Comrad",
    "Billy",
    "Jeroen Delodder b2b Neon",
    "EMILIJA",
    "Yves Deruyter",
    "Maraschino",
    "Le Swamp (Jan Paternoster)",
    "Mirage",
    "BAVR b2b DC Noises",
    "DJ Chibi Ichigo",
    "Kingfishr",
    "Wolf Alice",
    "The Last Dinner Party",
    "Royel Otis",
    "Teddy Swims",
    "Lewis Capaldi",
    "The xx",
    "Good Neighbours",
    "Social Distortion",
    "Viagra Boys",
    "Franz Ferdinand",
    "FKA twigs",
    "Charlotte de Witte",
    "ISE",
    "High Hi",
    "Paris Paloma",
    "Kae Tempest",
    "Agnes Obel",
    "Lauren Spencer Smith",
    "overpass",
    "Cardinals",
    "Keo",
    "Scene Queen",
    "Radio Free Alice",
    "The Warning",
    "Many More",
    "ROM¥",
    "Deco b2b Mosoo",
    "MATTN",
    "Henri PFR",
    "Viktor",
    "She The DJ",
    "Jens De Ruyte (SONS)",
    "MEROL (Ratkapje)",
    "Helena Lauwaert",
    "Mickael Karkousse b2b John Noseda",
    "LANDMVRKS",
    "Palaye Royale",
    "Kneecap",
    "Reneé Rapp",
    "Halsey",
    "Gorillaz",
    "Twenty One Pilots",
    "Harry Mack",
    "Dogstar",
    "The Haunted Youth",
    "Beirut",
    "Matt Berninger",
    "Pixies",
    "Linka Moja",
    "Adrian Quesada's Trio Asesino",
    "Don West",
    "Kokoroko",
    "VOILÀ",
    "CMAT",
    "The New Eves",
    "Man/Woman/Chainsaw",
    "Bleech 9:3",
    "Florence Road",
    "Ecca Vandal",
    "The Reytons",
    "DINO",
    "Isa Roos",
    "Paul Elstak ft. Jebroer",
    "Karakals",
    "Nina Black",
    "MAE.LIE b2b Synoxis",
    "Kids With Buns (DJ set)",
    "Hakimm",
    "Aili & Orson (DJ set)",
    "Alycia Bezgo",
    "Boy & Girl",
    "Kaat Van Stralen",
    "Bad Nerves",
    "SONS",
    "Rise Against",
    "A Perfect Circle",
    "Moby",
    "The Cure",
    "Darren Kiely",
    "Sierra Ferrell",
    "Cory Wong",
    "Mogwai",
    "David Byrne",
    "Paul Kalkbrenner",
    "Tsar B",
    "Dressed Like Boys",
    "Jessie Murph",
    "Joy Crookes",
    "Ethel Cain",
    "HAEVN",
    "Chezile",
    "Westside Cowboy",
    "NewDad",
    "Last Train",
    "House Of Protection",
    "Psychonaut",
    "Diètro",
    "Palmera",
    "La Fuente",
    "DJ F.R.A.N.K.",
    "Jordy",
    "Lennert Wolfs",
    "Kleinefrigo",
    "JANUS",
    "Séa",
    "Prinsezy",
    "Charlotte Adigéry"
  ]
};
